sudo: false
language: python
python:
  - '2.7'
cache:
  directories:
    - "$HOME/.pip-cache/"
install:
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --include molo.globalsite ^globalsite/
  - cp test_settings.py testapp/testapp/settings/local.py
  - cp -r molo/globalsite/geoip_db/ testapp/testapp/geoip_db
  - flake8 testapp
  - pip install -e testapp
  - py.test --cov=molo
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: isdKUhi7DBt+gpP4Ks+PJA4tbKAiMVlLZcwSESIjnu2bNXNbRNASqzU1BvuC//FsO86vZOSC1nPchQvEO+I6FjmGvXjnYbdEt7GtJGcmS4n/Hp/6lsouvdmabJA1ASdZqOL+yEdWQmBN0jEoyzoGMxFK9tu22+oH+2w4HX5bdPa9wt1/6jsuJ8qlXKRXr/+r3o8zOSBjmpe0G4mjjDUXTxVbIT7UDoRv6xbLhUcdzcW1jLraatpLpggGSpogR2Cdv0cBxTRQpBE688IRSQd1zoDlJQKalPh7b8qlwIsHhuj9vgT8ofy25LAhbG7Gb/gSnOQQOQF0TZSWCszq1W54yAfwkBAp+BJdngx5W8kp8m4LPSL7eFtcaIdGA3sxrIGewO1cEYwDyb6wYq2gZ+TnevJ0NC/Sf9U5Hh0nnrubsJvLX07drMRQt6PwsUCF42YmZYyQ8sUIjJYT0+ES9WdbrdEoZvLdd3CS0x9rEGrchBwO2jBa07AGSxmA7zFhKO11Hb9Q0/6iABeeZ0sdMwQnwVMWI4vboxMv7uWZ4CCkE1q26dOP1J9jyNRkD4c0zeyphYn5INwZhCGIjbZAgnyI9H05zI9XMd/jlfkyjMgk/+UEvTx+0fgHxyuQ9Em5rJuuhERBd3fzOuQF21OV9/06ASyGghlbln4mqnAgQkppTnU=
  on:
    tags: true
    all_branches: true
